# Creates jira tickets for new github issues to help triage
name: Jira Issue Creator

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-18.04
    environment: Jira
    name: SDK Bot Jira Issue Creation
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create issue
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: ${{ secrets.JIRA_PROJECT }}
          issuetype: Task
          summary: |
            [SDK - JS] ${{ github.event.issue.title }}
          description: |
            ${{ github.event.issue.url}}
          fields: '{
            "customfield_10006": 1039,
            "customfield_11481": {"value": "Data Management"},
            "customfield_11200": {"value": "SDK"},
            "labels": ["js"]
          }' # sprint, pillar, pod, labels

      - name: Log created issue
        run: echo "Issue AMP-${{ steps.create.outputs.issue }} was created"
