name: Lint

on: [pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: 14.x
        os: macOS-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --network-timeout 300000

      - name: Prettier check
        run: |
          yarn run lint:prettier

      - name: Eslint check
        run: |
          yarn run lint:eslint
