name: Lint

on: pull_request

jobs:
  lint-check:
    name: Check for ESLint + Prettier Violations
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: node_modules cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 22.x

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --network-timeout 300000

      - name: Prettier check
        run: |
          yarn run lint:prettier

      - name: Eslint check
        run: |
          yarn run lint:eslint
